newPRWelcomeComment: >
  Yerelleştirilmiş içeriğimize katkıda bulunduğunuz için teşekkür ederiz! 
  İçeriğimize yapılan tüm katkıların aşağıdaki yönergelere uygun olması gerekiyor:
  1. Metnin İngilizceden başka bir dile çevrildiğinde nasıl olması gerektiğini açıklayan [Microsoft Dil Stili Kılavuzu](https://www.microsoft.com/Language/StyleGuides).
  2. [Microsoft Dil Portalı](https://www.microsoft.com/language) Microsoft ürünlerinde kullanılan İngilizce teknoloji **terimlerini** ve bunların çevirilerini sağlıyor.
  Sürekli büyüyen Yerelleştirme Topluluğumuza katıldığınızda [Topluluk Yerelleştirme Wiki'si](https://github.com/Microsoft/Localization/wiki) adresini ziyaret ederek Topluluk Yerelleştirme Programı ve programımıza katkıda bulunabileceğiniz diğer yollar hakkında bilgi edinin. Ayrıca bu sayfada PR onay sürecini ve bazı <PR yönetimi> ipuçlarını da paylaşıyoruz.
  Katkıda bulunmayı sürdürün ve <yerelleştirme> katkılarınızdan puanlar kazanarak [Katkıda Bulunanlar Puan Tablosu](https://microsoftl10n.github.io/) sıralamasında daha yüksek düzeylere ulaşın!

  Microsoft Geliştirici İlişkileri Uluslararası Grubu
